---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-deployment
  namespace: development
  labels: 
    app: kubeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: kubeapp-container
        image: docker.io/pcgorantla/kubeapp:jib
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
 